[2025-06-15 18:19:04,481] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:19:02.311618+00:00 [queued]>
[2025-06-15 18:19:04,492] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:19:02.311618+00:00 [queued]>
[2025-06-15 18:19:04,492] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-06-15 18:19:04,492] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2025-06-15 18:19:04,492] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-06-15 18:19:04,544] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_ingestion> on 2025-06-15T18:19:02.311618+00:00
[2025-06-15 18:19:04,546] {standard_task_runner.py:52} INFO - Started process 114 to run task
[2025-06-15 18:19:04,548] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Job_dag', 'data_ingestion', '2025-06-15T18:19:02.311618+00:00', '--job-id', '85', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/churn_dag.py', '--cfg-path', '/tmp/tmpe99c1chc', '--error-file', '/tmp/tmp_4izt3uv']
[2025-06-15 18:19:04,549] {standard_task_runner.py:77} INFO - Job 85: Subtask data_ingestion
[2025-06-15 18:19:04,676] {logging_mixin.py:104} INFO - Running <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:19:02.311618+00:00 [running]> on host c455ceb3e41f
[2025-06-15 18:19:04,882] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Job_dag
AIRFLOW_CTX_TASK_ID=data_ingestion
AIRFLOW_CTX_EXECUTION_DATE=2025-06-15T18:19:02.311618+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-15T18:19:02.311618+00:00
[2025-06-15 18:19:04,896] {logging_mixin.py:104} INFO - Conection Testing123
[2025-06-15 18:19:04,896] {logging_mixin.py:104} INFO - <connection object at 0x7fffb0da2548; dsn: 'user=myuser password=xxx dbname=cust_churn_stg host=host.docker.internal port=6543', closed: 0>
[2025-06-15 18:19:04,899] {logging_mixin.py:104} INFO - Old data deleted.
[2025-06-15 18:19:05,184] {logging_mixin.py:104} INFO - CSV data inserted into Postgres successfully.
[2025-06-15 18:19:05,185] {python.py:151} INFO - Done. Returned value was: None
[2025-06-15 18:19:05,228] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Job_dag, task_id=data_ingestion, execution_date=20250615T181902, start_date=20250615T181904, end_date=20250615T181905
[2025-06-15 18:19:05,333] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15 18:19:05,347] {local_task_job.py:151} INFO - Task exited with return code 0
