[2025-06-15 18:15:58,417] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:15:57.034931+00:00 [queued]>
[2025-06-15 18:15:58,431] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:15:57.034931+00:00 [queued]>
[2025-06-15 18:15:58,432] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-06-15 18:15:58,432] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2025-06-15 18:15:58,432] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-06-15 18:15:58,489] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_ingestion> on 2025-06-15T18:15:57.034931+00:00
[2025-06-15 18:15:58,492] {standard_task_runner.py:52} INFO - Started process 131 to run task
[2025-06-15 18:15:58,494] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Job_dag', 'data_ingestion', '2025-06-15T18:15:57.034931+00:00', '--job-id', '81', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/churn_dag.py', '--cfg-path', '/tmp/tmpwn5qilx_', '--error-file', '/tmp/tmpcgpm5sdy']
[2025-06-15 18:15:58,494] {standard_task_runner.py:77} INFO - Job 81: Subtask data_ingestion
[2025-06-15 18:15:58,628] {logging_mixin.py:104} INFO - Running <TaskInstance: Job_dag.data_ingestion 2025-06-15T18:15:57.034931+00:00 [running]> on host c455ceb3e41f
[2025-06-15 18:15:58,853] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Job_dag
AIRFLOW_CTX_TASK_ID=data_ingestion
AIRFLOW_CTX_EXECUTION_DATE=2025-06-15T18:15:57.034931+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-15T18:15:57.034931+00:00
[2025-06-15 18:15:58,870] {logging_mixin.py:104} INFO - Conection Testing123
[2025-06-15 18:15:58,873] {logging_mixin.py:104} INFO - <connection object at 0x7fffb0da2548; dsn: 'user=myuser password=xxx dbname=cust_churn_stg host=host.docker.internal port=6543', closed: 0>
[2025-06-15 18:15:58,877] {logging_mixin.py:104} INFO - Old data deleted.
[2025-06-15 18:15:59,161] {logging_mixin.py:104} INFO - CSV data inserted into Postgres successfully.
[2025-06-15 18:15:59,162] {python.py:151} INFO - Done. Returned value was: None
[2025-06-15 18:15:59,204] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Job_dag, task_id=data_ingestion, execution_date=20250615T181557, start_date=20250615T181558, end_date=20250615T181559
[2025-06-15 18:15:59,314] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-15 18:15:59,334] {local_task_job.py:151} INFO - Task exited with return code 0
