[2025-06-16 02:56:26,492] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-16T02:56:24.679655+00:00 [queued]>
[2025-06-16 02:56:26,554] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Job_dag.data_ingestion 2025-06-16T02:56:24.679655+00:00 [queued]>
[2025-06-16 02:56:26,554] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-06-16 02:56:26,554] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2025-06-16 02:56:26,554] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-06-16 02:56:26,572] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_ingestion> on 2025-06-16T02:56:24.679655+00:00
[2025-06-16 02:56:26,575] {standard_task_runner.py:52} INFO - Started process 151 to run task
[2025-06-16 02:56:26,577] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Job_dag', 'data_ingestion', '2025-06-16T02:56:24.679655+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/churn_dag.py', '--cfg-path', '/tmp/tmph45wsbul', '--error-file', '/tmp/tmp3rjij5nn']
[2025-06-16 02:56:26,578] {standard_task_runner.py:77} INFO - Job 7: Subtask data_ingestion
[2025-06-16 02:56:26,708] {logging_mixin.py:104} INFO - Running <TaskInstance: Job_dag.data_ingestion 2025-06-16T02:56:24.679655+00:00 [running]> on host 00c15d6be3a5
[2025-06-16 02:56:26,920] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Job_dag
AIRFLOW_CTX_TASK_ID=data_ingestion
AIRFLOW_CTX_EXECUTION_DATE=2025-06-16T02:56:24.679655+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-16T02:56:24.679655+00:00
[2025-06-16 02:56:26,946] {logging_mixin.py:104} INFO - Conection Testing123
[2025-06-16 02:56:26,946] {logging_mixin.py:104} INFO - <connection object at 0x7fffb0da5548; dsn: 'user=myuser password=xxx dbname=cust_churn_stg host=host.docker.internal port=6543', closed: 0>
[2025-06-16 02:56:26,960] {logging_mixin.py:104} INFO - Old data deleted.
[2025-06-16 02:56:27,294] {logging_mixin.py:104} INFO - CSV data inserted into Postgres successfully.
[2025-06-16 02:56:27,294] {python.py:151} INFO - Done. Returned value was: None
[2025-06-16 02:56:27,337] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Job_dag, task_id=data_ingestion, execution_date=20250616T025624, start_date=20250616T025626, end_date=20250616T025627
[2025-06-16 02:56:27,449] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-16 02:56:27,454] {local_task_job.py:151} INFO - Task exited with return code 0
